/**
 * Generate a TypeScript module that exports the @ifc-lite/wasm binary
 * as a base64-encoded string. This allows the Power BI sandbox to load
 * the WASM without a separate network request.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const wasmPath = resolve('node_modules/@ifc-lite/wasm/pkg/ifc-lite_bg.wasm');
const outPath = resolve('src/wasm-inline.ts');

try {
    const wasmBytes = readFileSync(wasmPath);
    const base64 = wasmBytes.toString('base64');

    const module = `// AUTO-GENERATED by scripts/inline-wasm.mjs — do not edit
// Contains @ifc-lite/wasm binary as base64 for Power BI sandbox compatibility
const WASM_BASE64 = "${base64}";

export function getWasmBytes(): Uint8Array {
    const binary = atob(WASM_BASE64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
    }
    return bytes;
}
`;

    writeFileSync(outPath, module, 'utf8');
    console.log(`[inline-wasm] Generated ${outPath} (${(base64.length / 1024).toFixed(0)} KB base64)`);
} catch (err) {
    console.warn('[inline-wasm] Could not generate inline WASM:', err.message);
}
